### ISSUE TITLE
1>CSC : error SI0000: Exception: The hintName contains an invalid character ':' at position 13.

### ISSUE THREAD

**Issue by ignatandrei** [hermanussen/JsonByExampleGenerator#3] opened 2021-03-11 04:36 UTC
Sometime, at the second compilation , it gives me 
1>CSC : error SI0000: Exception: The hintName contains an invalid character ':' at position 13.

I think that is from

 context.AddSource(GetSourceFileName(namespaceName, jsonFile.Path),
                        SourceText.From(generatedCode, Encoding.UTF8));

Could you modify
private string GetSourceFileName(string namespaceName, string path)
        {
            var fullPath = Path.GetFullPath(path)
                .Replace(Path.GetFullPath("."), string.Empty)
                .Replace("/", "_")
                .Replace("\\", "_")
                .Replace(".", "_");

            return $"{namespaceName}_{fullPath.Trim('_')}.gen.cs";
        }

to take just the file name of the jsonFile  ?

Something like 
var fullPath = Path.GetFileNameWithoutExtension(path)

We do not need namespace and others - it is just a hint. 
And , if we want to see, we can put in csproj

`<PropertyGroup> 
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
`

**Comment by hermanussen** [comment] 2021-03-12 19:36
Thanks, that's a good idea. Fixed and released as v0.8.1

**Comment by ignatandrei** [comment] 2021-03-13 05:56
Does not work  Same error .  Contains still : 
( I do not see the code modified in what I say) 
Please at least make 

```
private string GetSourceFileName(string path)
        {
            var fullPath = Path.GetFullPath(path)
                .Replace(Path.GetFullPath("."), string.Empty)
                .Replace("/", "_")
                .Replace("\\", "_")
                .Replace(".", "_")
//add this line
                .Replace(":", "_");



            return $"{fullPath.Trim('_')}.gen.cs";
        }


```

**Comment by hermanussen** [comment] 2021-03-13 11:41
Ah, sorry. I thought removing the namespace argument would be enough. I'll take another go at it.

Honestly, it would be better if I could reproduce the issue. I suspect you are using an absolute path to include a file in the compilation (instead of a relative path). Am I right?

**Comment by ignatandrei** [comment] 2021-03-13 12:40
No. I could show you the code, if you want

**Comment by ignatandrei** [comment] 2021-03-13 12:40
#

**Comment by ignatandrei** [comment] 2021-03-13 12:41
In the meantime, could you modify and re-deploy?

**Comment by hermanussen** [comment] 2021-03-13 13:08
I did, but the CI build is now failing. I'll look into it soon (a bit busy right now).

**Comment by ignatandrei** [comment] 2021-03-13 14:16
Do not rush. Better safe than sorry :-)

**Comment by hermanussen** [comment] 2021-03-13 21:18
Should work now. Please use v0.8.2.

Please reopen if the issue is still not fixed.

**Closed as completed by hermanussen** 2021-03-13 21:18 UTC

**Comment by ignatandrei** [comment] 2021-03-13 22:27
Now a different error:

1>CSC : error CS0016: Could not write to output file 'E:\ignatandrei\Presentations\2021\RoslynSourceCodeGenerators\code\JsonToClass\src\JsonToClass\JsonToClass\obj\Generated\JsonByExampleGenerator.Generator\JsonByExampleGenerator.Generator.JsonGenerator\E__ignatandrei_Presentations_2021_RoslynSourceCodeGenerators_code_JsonToClass_src_JsonToClass_JsonToClass_Persons_json.gen.cs' -- 'Could not find a part of the path 'E:\ignatandrei\Presentations\2021\RoslynSourceCodeGenerators\code\JsonToClass\src\JsonToClass\JsonToClass\obj\Generated\JsonByExampleGenerator.Generator\JsonByExampleGenerator.Generator.JsonGenerator\E__ignatandrei_Presentations_2021_RoslynSourceCodeGenerators_code_JsonToClass_src_JsonToClass_JsonToClass_Persons_json.gen.cs'.'



This occurs just from VS , with rebuild all ( ! ), not from dotnet build

I have attached the project. ( the sln is at localized at E:\ignatandrei\Presentations\2021\RoslynSourceCodeGenerators\code\JsonToClass\src\JsonToClass )

[JsonToClass.zip](https://github.com/hermanussen/JsonByExampleGenerator/files/6135706/JsonToClass.zip)

**Comment by ignatandrei** [comment] 2021-03-13 22:27
And I do not have righs to open the issue ;-)

**Comment by ignatandrei** [comment] 2021-03-13 22:32
Now the name of the namespace is dependent of the folder path. Could you not pluralize and just put into the namespace of the assembly ?

**Comment by ignatandrei** [comment] 2021-03-13 22:33
For example, now the namespace is 

using JsonToClass.Json.C.D.JsonToClass.JsonToClass.Persons;

if the .csproj is at

C:\d\JsonToClass\JsonToClass
